### ISSUE TITLE
pypi archive is missing requirements.txt

### ISSUE THREAD

**Issue by geromueller** [dopevog/pytrend#1]
When installing via pip, setup.py cannot find requirements.txt:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

It looks like it is missing from the archive.

**Comment by will-tam** [comment]
Hello.

I confirm, i have the same exception raised:

# python3 -m pip install pytrend
Collecting pytrend
  Downloading pytrend-0.3.tar.gz (8.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wypyajz/pytrend_0fdbfc52ef30422196feb469dea86547/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wypyajz/pytrend_0fdbfc52ef30422196feb469dea86547/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-unr91scs
         cwd: /tmp/pip-install-_wypyajz/pytrend_0fdbfc52ef30422196feb469dea86547/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_wypyajz/pytrend_0fdbfc52ef30422196feb469dea86547/setup.py", line 31, in <module>
        install_requires=requirements(filename="requirements.txt"),
      File "/tmp/pip-install-_wypyajz/pytrend_0fdbfc52ef30422196feb469dea86547/setup.py", line 14, in requirements
        with io.open(filename, encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/47/50/9e304668e3554f8e338a791ed22a1811243a23b24b8d3868d78145316021/pytrend-0.3.tar.gz#sha256=87ed64ab51ff1450e1030344617fa076685a0c1e75d3498b5430b0b906e02919 (from https://pypi.org/simple/pytrend/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Best regards.
